### ISSUE TITLE
Again broken Trashable items - when container is horizontale scrolled

### ISSUE THREAD

**Issue by JanJohanX** [clauderic/dnd-kit#535] opened 2021-12-02 07:25 UTC
![Peek 2021-12-02 08-24](https://user-images.githubusercontent.com/44831820/144376637-d36ddcaa-30cd-42b8-bc90-36947719e3aa.gif)

**Comment by clauderic** [comment] 2021-12-12 22:50
Duplicate of #43, will be fixed by https://github.com/clauderic/dnd-kit/pull/518

**Closed by clauderic** 2021-12-12 22:50 UTC
