### ISSUE TITLE
Incorrect `event.delta` on `onDragEnd` within a scrollable container

### ISSUE THREAD

**Issue by BarrBozzO** [clauderic/dnd-kit#707] opened 2022-04-20 07:46 UTC
### Issue/Bug description:
Using @dnd-kit/core `useDraggable` to implement a simple drag-and-drop effect within a scrollable container.
While dragging - `transform` value returned from `useDraggable` is correct, but `onDragEnd`  `event.delta` has wrong values if scroll offset is non-zero.

### To reproduce:
Here is a sandbox link: https://codesandbox.io/s/distracted-dust-6eq47v?file=/src/Draggable.js:247-344
You can try to slightly scroll down and try dragging the element. Once "dragging" is finished - element will be placed incorrectly

Video demonstration of the bug: https://www.loom.com/share/a2f0129ece6847248c5ac04ed7d6837b

### Expected behavior:
Expected to see correct `event.delta` values on`onDragEnd`.

**Comment by clauderic** [comment] 2022-04-20 14:59
This is fixed by [this commit](https://github.com/clauderic/dnd-kit/commit/a41e5b8eff84f0528ffc8b3455b94b95ab60a4a9), which will be part of the next major release https://github.com/clauderic/dnd-kit/commit/a41e5b8eff84f0528ffc8b3455b94b95ab60a4a9

> Fixed a bug with the `delta` property returned in `onDragMove`, `onDragOver`, `onDragEnd` and `onDragCancel`. The `delta` property represents the `transform` delta since dragging was initiated, along with the scroll delta. However, due to an oversight, the `delta` property was actually returning the `transform` delta and the _current_ scroll offsets rather than the scroll _delta_.

You can try it by upgrading to using the @dnd-kit packages tagged with `next` on npm:
https://codesandbox.io/s/inspiring-tharp-o7jb2v?file=/package.json

**Comment by mendelgratt** [comment] 2022-05-19 21:30
Hey @clauderic 
I had the same issue and it got fix using the next version as you mention. The problem now is when I drag and drop and element, the internal content ends up with an opacity 0, hiding it. 
We tried with the old version and this doesn't happen, but we have the scroll issue. 
We can fix that quite easily setting the opacity to 1 then it's not dragging, but I was wondering what the root cause is.

Thanks for the his amazing library!

**Comment by mauriciocreek** [comment] 2022-05-19 23:03
Hey @clauderic
I had the same issue and it got fix using the next version as you mention. The problem now is when I drag and drop and element, the internal content ends up with an opacity 0, hiding it.
We tried with the old version and this doesn't happen, but we have the scroll issue.
We can fix that quite easily setting the opacity to 1 then it's not dragging, but I was wondering what the root cause is.

Thanks for the his amazing library

**Closed** 2022-05-21 01:56 UTC
