### ISSUE TITLE
useDndMonitor onDragStart not called when there is an activationConstraint and collisionDetection is closestCorners

### ISSUE THREAD

**Issue by mkelliher** [clauderic/dnd-kit#369] opened 2021-07-20 18:20 UTC
## Repro

1. Create a `DndContext` with:
    - A pointer sensor with an activation constraint: `useSensor(PointerSensor, { activationConstraint: { distance: 10 } })`
    - `collisionDetection={closestCorners}`
    - A draggable and a droppable component
2. Somewhere in a child component within the context, put `useDndMonitor({ onDragStart: () => console.log('useDndMonitor: onDragStart') })`
3. Notice that the `useDndMonitor: onDragStart` is not logged when a drag is started.

I have set up the repro in a CodeSandbox here: https://codesandbox.io/s/dnd-kit-ondragstart-bug-zysht?file=/src/App.js

When you drag the item by its red drag handle, take a look at the console logs. You will see that the `DndContext: onDragStart` is called, but the `useDndMonitor: onDragStart` is not.

## Workaround

I found that this issue does not occur if the `collisionDetection` function returns `null` at the start of the drag. So the workaround is to have `collisionDetection` always return `null` until `DndContext: onDragStart` is called. Then, after that, have the function return its regular results (i.e., `closestCorners`).

See the above CodeSandbox for an example of the workaround (in `App.js` use `collisionDetection={collisionDetectionWorkaround}`).

**Comment by clauderic** [comment] 2021-07-22 01:45
This is fixed by this commit, which will be released in the next major version: 
https://github.com/clauderic/dnd-kit/commit/05d6a78a17cbaacd8dffed685dfea5a6ea3d38a8#diff-c4e29cc1eb5f250d1c1ff78d14b5785fb2a003b7aa2c8821dfecf20bc9d86325R387-R391

You can follow the release PR here #31 

If you're eager to jump to the next version before it's released, you can install versions tagged with `@next` on npm.

See this forked sandbox where the issue is no longer reproducible if you upgrade to the `@next` version of `@dnd-kit/core` https://codesandbox.io/s/dnd-kit-ondragstart-bug-forked-utdlw?file=/src/Draggable.js

**Closed by clauderic** 2021-07-22 01:45 UTC
