### ISSUE TITLE
Spontaneous horizontal scrolling when using useSortable

### ISSUE THREAD

**Issue by ksimons** [clauderic/dnd-kit#78] opened 2021-02-05 12:09 UTC
This issue is visible in the "Many items" multiple container example. Just pick up a single card starts the whole board scrolling rapidly to the right. I guess it's because the card is near the right edge, but in my experimentation it's very hard to get control of that horizontal scrolling if the board is wider than the screen.

Chrome/macOS

![ezgif-7-1f35550d9661](https://user-images.githubusercontent.com/935932/107031982-581c7900-67b3-11eb-9f93-addec76e82f4.gif)

Is it possible to tune the scrolling behavior as a client of dnd-kit?

**Comment by clauderic** [comment] 2021-02-05 19:51
Duplicate of #23. Generally I think it's a bit tricky to find a one-size-fits-all strategy for auto-scrolling. I think in the future this should be a bit more extensible, and have either a pointer coordinates based strategy or a strategy that is based on the bounding rect of the dragged element

**Closed by clauderic** 2021-02-05 19:51 UTC
