### ISSUE TITLE
Proper examples for each preset

### ISSUE THREAD

**Issue by ABSanthosh** [clauderic/dnd-kit#624] opened 2022-02-10 05:48 UTC
@clauderic 
This is a great library but the documentation is quite lacking. The only official example is so much bloated and ridiculously linked.

For instance, The [MultipleContainers](https://github.com/clauderic/dnd-kit/blob/master/stories/2%20-%20Presets/Sortable/4-MultipleContainers.story.tsx) example in the stories. In the storybook link for the [demo](https://5fc05e08a4a65d0021ae0bf2-goamnjvxea.chromatic.com/?path=/story/presets-sortable-multiple-containers--basic-setup), the demos are properly nested and easy to understand what the library is capable of doing, But when you want to understand how it works, Its almost impossible.

The whole sub folder for MultipleContainers exampe in storybook is in [MultipleConainers.tsx](https://github.com/clauderic/dnd-kit/blob/master/stories/2%20-%20Presets/Sortable/MultipleContainers.tsx) and it is written in a way that with just props from [MultipleContainers.story.tsx](https://github.com/clauderic/dnd-kit/blob/master/stories/2%20-%20Presets/Sortable/4-MultipleContainers.story.tsx), multiple examples can be made but unfortunately when you try to build a component similar to, say MultipleContainers > Basic Setup, there are like a couple dozen of undocumented helper components(`Item, Container, ContainerProps`) and a ton of props and states and functions which is not used in this specific example.

## Please take some time and re-write the examples in separate folders that contains all the needed components inside the folder. This would greatly help the developers and attract more people. This is genuinely a great package and is in par with React-beautiful-dnd or even better than that in performance.

If that's a lot to ask, atleast make a separate codesandbox for each example. You built the library and I don't think building already build examples again will be an issue. I can also help in doing so but without proper documentation in the stories, even that's impossible for me.

Hope you can do something about this.

**Comment by kevinletchford** [comment] 2022-02-12 17:34
I agree the sort examples are quite unwieldy to work through.

I am going through the process of taking one of the examples and striping it down:

https://codesandbox.io/s/dnd-kit-multiple-columns-uog1x?file=/src/Example.tsx

**Comment by ABSanthosh** [comment] 2022-02-13 14:38
@kevinletchford That's great! I'm doing the same but I've struck a dead end now. The smooth transition of cards between panels is not working no matter what I do. A little bit of documentation in the example could have helped a lot. plus, the example uses a weird data format like using the key as column id and stuff. Porting it to a custom data format has been a pain.

Check mine out and see if that helps you in anyway.
https://github.com/ABSanthosh/dnd-kit-BasicMultiContainerPreset

Hopefully @clauderic does some documentation in the examples soon.

**Comment by nifte** [comment] 2022-02-19 09:54
We really need individual codesandboxes or better documentation for each example in the storybook. Trying to reverse engineer the all-in-one `<Sortable />` example component is a nightmare.

**Comment by clauderic** [comment] 2022-02-21 14:51
Duplicate of https://github.com/clauderic/dnd-kit/issues/425

I agree with the feedback here, but this isn't something I have time to work on at the moment. PRs are welcome.

**Closed by clauderic** 2022-02-21 14:51 UTC

**Comment by srph** [comment] 2022-03-04 00:41
Hi folks, just leaving this [here](https://github.com/srph/smarf/blob/bbf36b6c0d11579398c87cde6210008e76b6266c/src/root/BoardWorkspace/useGridCollisionDetection.ts) in case you find it useful. I hacked on it for two mornings so it definitely needs to be cleaned up!

It makes the collision detection more reusable, and might make it simpler to understand. My use-case is much simpler compared to the examples: a sortable grid between multiple containers. The container themselves don't need to be dragged.

**Comment by vaynevayne** [comment] 2023-05-05 07:46
> 
Give up the library and continue to maintain react-sortable-hoc, which doesn't take you much time, just merge pr

**Comment by vaynevayne** [comment] 2023-05-05 07:48
> Too complicated to understand your code, it is better to directly implement the native
