### ISSUE TITLE
Collision detection in sortable multi-containers with many items

### ISSUE THREAD

**Issue by xReaven** [clauderic/dnd-kit#73] opened 2021-01-27 14:30 UTC
Hi dnd master,

I'm trying to do something like [this example](https://5fc05e08a4a65d0021ae0bf2-zditmhymjz.chromatic.com/?path=/story/presets-sortable-multiple-containers--many-items) with even more complexity within each columns (multi-level list...) but for the sake of this issue, the example is enough.

**Describe the bug (Required)**
When there is a lot of items in the first column (say A, so items are A1, A2...) and a very few in the second column (say B, with only B1 item), then a lot in the third column C, if you pick an item from A that is very down in the container, like A15 and try to put it in the B column, the A column or the C column scrolls up until the collision detect B1.

The more items you have in A and C, the more the bug is visible.

I assume the top property of the dragged item is causing this issue or something like this, I haven't jumped into the code but I guess.

**Expected behavior (Required)**
When picking A246, dragging over B1, want to be able to drop above or below B1 without waiting the scroll goes up :)

Maybe a collision "with the cursor position" would be great ? (I'm not aware of what is possible or not)

Thanks for the reading,
Cya

**Comment by clauderic** [comment] 2021-01-29 03:09
Duplicate of #43

**Closed by clauderic** 2021-01-29 03:09 UTC

**Comment by xReaven** [comment] 2021-01-29 08:46
Not exactly, I can reproduce whatever the collision algorithm I'm using.
