### ISSUE TITLE
Is it possible to access `onDragEnd` in droppable region?

### ISSUE THREAD

**Issue by Shaddix** [clauderic/dnd-kit#173] opened 2021-03-30 05:19 UTC
My scenario is that whole app is wrapped into `DndContext`, and there's a list of items that could either be:
- sorted within that list
- dragged to a Calendar, where every day is a Droppable region

So, as in react-dnd, I'd like to have an ability to have an `onDragEnd` handler in `useDroppable` hook, so that each Calendar cell could know & handle the item that is dropped there. It seems that now I could get `onDragEnd` only from `<DndContext>` element, which is not convenient, since droppable regions are deeply nested.

For sure I could create my own separate context and use it to push onDragEnd to children, but I guess it'd be useful to have this built-in to dnd-kit itself.

**Comment by clauderic** [comment] 2021-03-30 21:27
@Shaddix agreed the current setup may not be ideal for large complex use-cases, though as you mentioned this can be solved by propagating these events through a context provider you define.

Long term, something similar to `react-dnd`'s solution to state monitoring could eventually be a nice addition indeed, though I don't have plans to work on this in the short term, there are other higher priority things I'd like to solve in the short term.

You can also have an effect run in your components that use `useDroppable` based on the `active` property of `useDndContext`, something like:

```ts
function Droppable(props) {
  const {} = useDroppable({id: props.id});
  const {active, over} = useDndContext();

  useEffect(() => {
    // do stuff
  }, [active, over]}
}
```

**Comment by clauderic** [comment] 2021-03-30 21:38
Going to close this issue as it is technically a duplicate of https://github.com/clauderic/dnd-kit/issues/58

**Closed by clauderic** 2021-03-30 21:38 UTC
Labels: enhancement, has workaround
