### ISSUE TITLE
SortableContext scrolling issues 

### ISSUE THREAD

**Issue by ohayojp** [clauderic/dnd-kit#128] opened 2021-03-12 06:51 UTC
I found two issues when using SortableContext and small viewport/container:
1) For small items near edges of scrolling container right after grabbing drag handle container will scroll up or down automatically making it very hard to to sort.
2) For bigger items (like row C in the example below) even if they are fully visible dragging will cause other items to jump up and down until item is moved away from it's original position.

Here is the codesanbox - https://codesandbox.io/s/dnd-kit-sorting-big-items-epgtd

**Comment by clauderic** [comment] 2021-03-16 01:37
Duplicate of #23

**Closed by clauderic** 2021-03-16 01:37 UTC
