### ISSUE TITLE
Trashable items - when container is horizontale scrolled

### ISSUE THREAD

**Issue by JanJohanX** [clauderic/dnd-kit#245] opened 2021-04-30 12:51 UTC
![Peek 2021-04-30 14-48](https://user-images.githubusercontent.com/44831820/116697409-70bbba00-a9c3-11eb-8104-a8d7dce87802.gif)

**Comment by clauderic** [comment] 2021-05-01 13:22
Duplicate of https://github.com/clauderic/dnd-kit/issues/61

**Closed by clauderic** 2021-05-01 13:22 UTC
