### ISSUE TITLE
Collision detection sometimes has errors

### ISSUE THREAD

**Issue by bobolittlebear** [clauderic/dnd-kit#523] opened 2021-11-24 06:22 UTC
I upgraded dnd-kit to the latest version today and found the following error:
https://user-images.githubusercontent.com/55129710/143185342-459aac14-319f-491a-b127-45f6db4feeae.mov

**Comment by clauderic** [comment] 2021-11-24 16:17
Was this working before? This seems like a duplicate of #43 to me and isn't a new issue / regression as far as I'm aware.

**Closed** 2022-01-06 23:54 UTC
Labels: more information required
