### ISSUE TITLE
Selecting an item in the multiple containers example autoscrolls to the right

### ISSUE THREAD

**Issue by Sorgrum** [clauderic/dnd-kit#97] opened 2021-02-20 15:50 UTC
If you resize your browser window to be the smallest width possible, and click on an item to drag (anywhere on the item), the window automatically scroll to the right.

The same behavior happens on mobile

[Example](https://drive.google.com/file/d/1Qp4G804M3RIJAUhZQr9waYnIpthl7Iz9/view?usp=sharing)

**Comment by clauderic** [comment] 2021-02-20 15:52
Duplicate of #23

**Closed by clauderic** 2021-02-20 15:52 UTC
