### ISSUE TITLE
Can't delete items from some containers in trashable items demo

### ISSUE THREAD

**Issue by sampl** [clauderic/dnd-kit#98] opened 2021-02-21 16:27 UTC
Hi y'all--first of all, I'm _extremely_ excited for this library, I think react drag and drop needs something exactly like this.

Try out the storybook, I couldn't delete some items in the Multiple Containers/Trashable Items demo. Items from the first column seem to work, but items from the others don't.

Mac OS & Chrome. Lmk if I can add more details.

Demo video: https://www.loom.com/share/f02bd16509d64500b2140ca121a9592a

**Comment by clauderic** [comment] 2021-02-21 16:29
Duplicate of #43

**Closed by clauderic** 2021-02-21 16:29 UTC

**Comment by sampl** [comment] 2021-02-21 16:31
Whoops didn't realize--thanks for the speedy reply @clauderic  :)
