### ISSUE TITLE
CSS transforms not considered on droppables

### ISSUE THREAD

**Issue by PhilippSpo** [clauderic/dnd-kit#250] opened 2021-05-03 12:02 UTC
We have a use case where our droppables are scaled and translated using a CSS transform. However, the `width`, `height`, `offsetLeft`, and `offsetTop` of the drop targets don't include the applied CSS transform.

Is there already some way to support this behavior that we didn't find in the documentation? 🤔 Something like using `getBoundingClientRect` under the hood?

**Comment by clauderic** [comment] 2021-05-03 13:46
Duplicate of https://github.com/clauderic/dnd-kit/issues/205

**Closed by clauderic** 2021-05-03 13:46 UTC
