### ISSUE TITLE
Code examples

### ISSUE THREAD

**Issue by mariusrak** [clauderic/dnd-kit#525] opened 2021-11-25 21:55 UTC
Hi, there are many great examples of how to use this awesome kit. And often times I find in storybook exactly same thing as I need to implement. But when I want to look at how to do it I get for example this:
```js
() => <MultipleContainers itemCount={5} vertical />
```
Which says absolutely nothing. If I want to understand how is this implemented I have to go through complex code which implements various scenarios and is influenced by various conditions. 

It would be really useful and helpful, if each scenario was isolated file with isolated code with no dependencies expect the library.
Would it be possible to change examples in this manner?

Thank you.

P.S. Also, getting to source code in story book is quite difficult and one has to be very attentive to find the code by clicking `Docs` and then finding small `Show code`. But that's more of storybook's issue, I guess.

**Comment by clauderic** [comment] 2021-11-26 15:52
Duplicate of #425 

This is definitely something that is planned, but to be honest it's _a lot_ of work and I don't have the bandwidth to do it.

PRs are welcome if you want to contribute to making the examples more legible.

**Closed by clauderic** 2021-11-26 15:52 UTC
