### ISSUE TITLE
Incorrect dragging item positioning

### ISSUE THREAD

**Issue by psd-coder** [clauderic/dnd-kit#529] opened 2021-11-28 19:48 UTC
Hey guys! `dnd-kit` is awesome, thank you for your work!
I have found one interesting behaviour/bug. Sometimes, when you drag item very fast you get incorrect position of dragging item (I mean original item which is become half transparent,  not `DragOverlay`) and it looks inconsistent. I noticed that in horizontal lists with variable items width, but could reproduce with basic setup too. I recorded video, where you can see this incorrect positioning (from the 11 second in the video)
https://www.loom.com/share/c5f2ba94ae7849df8032f063042f1c02

**Comment by KayhanB** [comment] 2021-11-29 15:44
First of all, I sincerely thank the creators of this library.
I included this library in the project I was working on a week ago and I wrote a component that allows developers to easily develop new dnd elements and render them dynamically (lazy) according to the user's data.
Everything works except for this problem. The problem occurs every time the dnd element is clicked and dragged quickly, but if it is dragged slowly after the first click, there is no problem.
When I first noticed the problem, I looked for the problem in my own works, but when I examined the examples in the documentation, I realized that the problem was caused by the library.
I hope I have provided information that will help you find a solution.
Thanks again for this awesome library.

**Comment by bnjmnt4n** [comment] 2021-11-30 10:40
This issue is a duplicate of https://github.com/clauderic/dnd-kit/issues/470.

**Comment by psd-coder** [comment] 2021-11-30 10:57
Yeah, it seems so

**Comment by clauderic** [comment] 2022-01-10 05:31
Fixed in https://github.com/clauderic/dnd-kit/pull/566

**Closed by clauderic** 2022-01-10 05:31 UTC
