### ISSUE TITLE
Dragging an item within a Sortable container resets its ancestor scroll position

### ISSUE THREAD

**Issue by dpavicic-ts** [clauderic/dnd-kit#100] opened 2021-02-22 14:34 UTC
I'm experiencing an issue when using [Sortable preset](https://docs.dndkit.com/presets/sortable) within a scrollable list. I have a scrollable list of items, where each item is a sortable container with sortable elements. If I scroll the list and try to reorder the elements, it resets the scroll position as soon as I start dragging, as you can see below.
![Screen Recording 2021-02-22 at 11 48 07 AM](https://user-images.githubusercontent.com/63050327/108721770-adca8280-7522-11eb-8d33-4378be9f2719.gif)

Here's the sandbox reproducing the issue: https://codesandbox.io/s/dnd-kit-scrolling-ancestor-issue-i55g1?file=/src/App.js

Is there a workaround to prevent this from happening with the existing API, or it might be a bug? 

Thanks in advance!

**Comment by clauderic** [comment] 2021-02-24 15:07
This looks like a duplicate of #23

**Closed by clauderic** 2021-02-24 15:07 UTC
