### ISSUE TITLE
Dragging does not work when there are few items in a container (dnd-kit storybook)

### ISSUE THREAD

**Issue by naman-ali** [clauderic/dnd-kit#423] opened 2021-08-16 04:04 UTC
Given two containers A(many items) and B(few items), when container A is scrolled to bottom, dragging from A to B does not work.

You can find this behavior in the following video that I took from the [dnd-kit many items example](https://5fc05e08a4a65d0021ae0bf2-mdsmdaavqx.chromatic.com/?path=/story/presets-sortable-multiple-containers--many-items).

https://user-images.githubusercontent.com/56988099/129509659-cc368801-00b6-40b9-88bb-9e0ee2a3ecf8.mp4

**Comment by oyzhen** [comment] 2021-08-16 10:08
Same problem.

**Comment by clauderic** [comment] 2021-08-19 18:51
This is a duplicate of #43, though that issue needs to be re-named. It's going to be the priority of the 5.0.x release of `@dnd-kit/core` to fix that issue.

**Closed by clauderic** 2021-08-19 18:51 UTC
