### ISSUE TITLE
Drag Overlay and scrolling container not working after scroll

### ISSUE THREAD

**Issue by damien-monni** [clauderic/dnd-kit#325] opened 2021-06-08 08:01 UTC
I don't know if it is related to #43, so I am opening a new issue.

I am having an issue with a simple drag and drop that is using a scrolling container. I tried to replicate the issue in the most simple way I could find here: https://codesandbox.io/s/dnd-kit-scroll-issue-iwxrm?file=/src/App.js

When the container is not scrolled, drag and drop works perfectly. But as soon as you scroll the container and try to drag and drop an item, it starts behaving weirdly. Sometime it even seems to randomly stops working as you can see in the following video:

https://user-images.githubusercontent.com/6009968/121145555-605af280-c83f-11eb-8d0c-d584f4363e79.mp4

Any hint or workaround for this issue would be fantastic!

Thanks

**Comment by clauderic** [comment] 2021-06-10 00:57
This is indeed a duplicate of #43, though thanks for the detailed issue report and replication sandbox

**Closed by clauderic** 2021-06-10 00:57 UTC
